#!/usr/bin/env python
import time
import rospy
import actionlib
from control_msgs.msg import *
from trajectory_msgs.msg import *
from sensor_msgs.msg import Joy
import urllib2
import cv2

JOINT_NAMES = ['ur5_arm_shoulder_pan_joint', 'ur5_arm_shoulder_lift_joint', 'ur5_arm_elbow_joint', 'ur5_arm_wrist_1_joint', 'ur5_arm_wrist_2_joint', 'ur5_arm_wrist_3_joint']

ZERO_THRESH = 0.00000001

Q1 = [1.57,-1.57,0,-1.57,0,0]
Q2 = [-1.57,-1.57,0,-1.57,0,0]
Q3 = [-1.57,-0.1745,-2.79,-1.57,0,0]
q = [-1.57,-0.1745,-2.79,-1.57,0,0]

client = None

def callback(data):
  
	rospy.loginfo('Left Stick Horiz: ' + str(data.axes[0]) + ' Left Stick Vert: ' + str(data.axes[1]) +' Right Stick Horiz: ' + str(data.axes[3]) +' Right Stick Vert: ' + str(data.axes[4]) + ' D-pad Horiz: ' + str(data.axes[6]) + ' D-pad Vert: ' + str(data.axes[7]))
	rospy.loginfo('A: ' + str(data.buttons[0]) + ' B: ' + str(data.buttons[1]) + ' X: ' + str(data.buttons[2]) + ' Y: ' + str(data.buttons[3]) + ' LB: ' + str(data.buttons[4]) + ' RB: ' + str(data.buttons[5]) + ' Back: ' + str(data.buttons[6]) + ' Start: ' + str(data.buttons[7]) + ' L3: ' + str(data.buttons[9]) + ' R3: ' + str(data.buttons[10]))
	rospy.loginfo('-----------------')

def main():
    	rospy.init_node("test_move", anonymous=True, disable_signals=True)
	rospy.Subscriber("/joy", Joy, callback)

	rospy.spin()

if __name__ == '__main__': main()

